### PR TITLE
Fix starting location bug

### PR DESCRIPTION
**Pull request by awaisdar001**

### CODE REVIEW

**Comment by awaisdar001** [comment]
@DawoudSheraz  Quick review. I found this issue while creating demo data ticket.

**Comment by DawoudSheraz** [comment]
It was originally FK, but we changed it to 1-1 as I had thought one trip can start from one location. But didn't realize the reverse, that many trips can start from one location. Good point

**Comment by DawoudSheraz** [comment]
We should generate ERD of the DB, just to confirm that all relations are correct now.

**Comment by awaisdar001** [comment]
> We should generate ERD of the DB, just to confirm that all relations are correct now.

Pls do that when you get a space.

**Pull request merged**
